package paivakirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.04.26 14:18:16 // Generated by ComTest
 *
 */
public class PaikatTest {



  // Generated by ComTest BEGIN
  /** testPaikat31 */
  @Test
  public void testPaikat31() {    // Paikat: 31
    Paikka paikka = new Paikka(); 
    assertEquals("From: Paikat line: 33", 1, paikka.getId()); 
    Paikka paikka2 = new Paikka(); 
    assertEquals("From: Paikat line: 36", 2, paikka2.getId()); 
    paikka.parse("3|CM"); 
    assertEquals("From: Paikat line: 39", "CM", paikka.getNimi()); 
    Paikka paikka3 = new Paikka(); 
    assertEquals("From: Paikat line: 42", 4, paikka3.getId()); 
    Paikat paikat = new Paikat(); 
    paikat.lisaa(paikka); 
    paikat.lisaa(paikka2); 
    paikat.lisaa(paikka3); 
    assertEquals("From: Paikat line: 49", "CM", paikat.annaPaikka(3)); 
    assertEquals("From: Paikat line: 51", 3, paikat.annaPaikkaId("CM")); 
    assertEquals("From: Paikat line: 53", 5, paikat.annaPaikkaId("Prisma")); 
  } // Generated by ComTest END
}