package paivakirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.04.26 14:19:12 // Generated by ComTest
 *
 */
public class PaikkaTest {



  // Generated by ComTest BEGIN
  /** testPaikka23 */
  @Test
  public void testPaikka23() {    // Paikka: 23
    Paikka paikka = new Paikka(); 
    assertEquals("From: Paikka line: 25", 1, paikka.getId()); 
    Paikka paikka2 = new Paikka(); 
    assertEquals("From: Paikka line: 28", 2, paikka2.getId()); 
    paikka.parse("3|CM"); 
    assertEquals("From: Paikka line: 31", "CM", paikka.getNimi()); 
    Paikka paikka3 = new Paikka(); 
    assertEquals("From: Paikka line: 34", 4, paikka3.getId()); 
  } // Generated by ComTest END
}