package paivakirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.04.26 14:21:12 // Generated by ComTest
 *
 */
public class TapahtumaTest {



  // Generated by ComTest BEGIN
  /** testTaytaTapahtuma30 */
  @Test
  public void testTaytaTapahtuma30() {    // Tapahtuma: 30
    Tapahtuma tapahtuma1 = new Tapahtuma(); 
    tapahtuma1.taytaTapahtuma(); 
    assertEquals("From: Tapahtuma line: 34", "Kauppareissu", tapahtuma1.getNimi()); 
    tapahtuma1.parse("4|Hevostalli|121.36510308800352|S-Market|10.02.2017|0|Maito oli loppu kaupasta"); 
    assertEquals("From: Tapahtuma line: 36", "Hevostalli", tapahtuma1.getNimi()); 
  } // Generated by ComTest END
}