package paivakirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.04.26 14:23:24 // Generated by ComTest
 *
 */
public class TilitTest {



  // Generated by ComTest BEGIN
  /** testTilit31 */
  @Test
  public void testTilit31() {    // Tilit: 31
    Tili tili = new Tili(); 
    assertEquals("From: Tilit line: 33", 1, tili.getId()); 
    Tili tili2 = new Tili(); 
    assertEquals("From: Tilit line: 36", 2, tili2.getId()); 
    tili.parse("3|Käyttötili|Ei ole rahaa"); 
    assertEquals("From: Tilit line: 39", "Käyttötili", tili.getNimi()); 
    Tili tili3 = new Tili(); 
    assertEquals("From: Tilit line: 42", 4, tili3.getId()); 
    Tilit tilit = new Tilit(); 
    tilit.lisaa(tili); 
    tilit.lisaa(tili2); 
    tilit.lisaa(tili3); 
    assertEquals("From: Tilit line: 49", "Käyttötili", tilit.annaTili(3)); 
  } // Generated by ComTest END
}