package paivakirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.04.26 14:23:01 // Generated by ComTest
 *
 */
public class TiliTest {



  // Generated by ComTest BEGIN
  /** testTili26 */
  @Test
  public void testTili26() {    // Tili: 26
    Tili tili = new Tili(); 
    assertEquals("From: Tili line: 28", 1, tili.getId()); 
    Tili tili2 = new Tili(); 
    assertEquals("From: Tili line: 31", 2, tili2.getId()); 
    tili.parse("3|Käyttötili|Ei ole rahaa"); 
    assertEquals("From: Tili line: 34", "Käyttötili", tili.getNimi()); 
    Tili tili3 = new Tili(); 
    assertEquals("From: Tili line: 37", 4, tili3.getId()); 
  } // Generated by ComTest END
}